type: firn_model
name: neem
parameters:
  path: /Users/ericm/Documents/Research/methane_noise_forcing/data/firn_filters/firn_filter_neem.csv
notes: NEEM closed-air porosity from Christo Buizert (notebook - explore_empirical_firn_filters.ipynb)