defaults:
  - _self_ # inherit global defaults

sites: [wdc05a]

defaults_for_observations: &defaults_for_observations
  mask_year: 1800

noise:
  duration_timeseries: 4750 # Duration of time series in years
  n_ens: 1000 # Number of ensemble members
  dt: 1 # Time step in years
  time_units: years
  output:
    format: netcdf

sampling:
  core_offset_flag: start # Offset for sampling at core points
  series_offset: 150 # Offset in years for sampling for spinup

paths:
  project_root: "/home/disk/p/emei/repos/methane_noise_forcing" # change this path to the cloned project directory
  data_dir: "${paths.project_root}/data"
  configs_dir: "${paths.project_root}/configs"

  figures_dir: "/home/disk/hermes3/emei/methane_noise_forcing/figures" # change this path
  
  noise_realizations_root: "/home/disk/hermes3/emei/methane_noise_forcing/noise_realizations" # change this path
  
  observations_root: "${paths.data_dir}/observations"
  observations_cultivated: "${paths.observations_root}/cultivated"
  observations_power_spectra: "${paths.observations_root}/power_spectra"

  firn_filters_root: "${paths.data_dir}/firn_filters"

io:
  wdc05a:
    input:
      file_path: "${paths.observations_cultivated}/mitchelletal2013_wdc05a.csv"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/mitchelletal2013_wdc05a_power_spectra.nc"
  wdc06a:
    input:
      file_path: "${paths.observations_cultivated}/mitchelletal2013_wdc06a.csv"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/mitchelletal2013_wdc06a_power_spectra.nc"
  gisp2:
    input:
      file_path: "${paths.observations_cultivated}/mitchelletal2013_gisp2.csv"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/mitchelletal2013_gisp2_power_spectra.nc"
  neem:
    input:
      file_path: "${paths.observations_cultivated}/rhodesandbrook2019_neem.tab"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/rhodesandbrook2019_neem_power_spectra.nc"