defaults:
  - noise: two_timescale
  - _self_ # inherit global defaults

sites: [wdc05a]

defaults_for_observations: &defaults_for_observations
  mask_year: 1800

noise:
  time_units: years
  output:
    format: netcdf

paths:
  project_root: "/Users/ericm/Documents/Research/methane_noise_forcing"
  data_dir: "${paths.project_root}/data"
  configs_dir: "${paths.project_root}/configs" 
  figures_dir: "${paths.project_root}/figures"
  
  # Derived paths (relative to project_root)
  noise_realizations_root: "${paths.data_dir}/noise_realizations"

  observations_root: "${paths.data_dir}/observations"
  observations_cultivated: "${paths.observations_root}/cultivated"
  observations_power_spectra: "${paths.observations_root}/power_spectra"

io:
  wdc05a:
    input:
      file_path: "${paths.observations_cultivated}/mitchelletal2013_wdc05a.csv"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/mitchelletal2013_wdc05a_power_spectra.nc"
  wdc06a:
    input:
      file_path: "${paths.observations_cultivated}/mitchelletal2013_wdc06a.csv"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/mitchelletal2013_wdc06a_power_spectra.nc"
  gisp2:
    input:
      file_path: "${paths.observations_cultivated}/mitchelletal2013_gisp2.csv"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/mitchelletal2013_gisp2_power_spectra.nc"
  neem:
    input:
      file_path: "${paths.observations_cultivated}/rhodesandbrook2019_neem.tab"
      <<: *defaults_for_observations
    power_spectra_path: "${paths.observations_power_spectra}/rhodesandbrook2019_neem_power_spectra.nc"